'''n = input('Digite algo e descubra o que é ')
print('O tipo primitivo é: ',type(n))
print('É um alphanumérico: ',n.isalpha())
print('Tem letras minusculas? ',n.isspace())
print('Tem letras maiusculas?', n.isupper())
print('É número? ', n.isnumeric())
print('É espaço? ',n.isspace()'''

#Revisão
print('-=-' * 10)
print('Descubra o que representa!')
print('-=-' * 10)
x = input('Digite algo e descubra o que é: ')
print('O tipo é primitivo é: ', type(x))
print('Só tem letras maiúsculas? ', x.isupper())
print('Só tem letras minúsculas? ', x.islower())
print('É alphanumérico? ', x.isalnum())
print('É imprimivel? ', x.isprintable())
print('É numérico? ', x.isnumeric())
print('É espaço? ', x.isspace())